/**
 * Sequence Settings page (view + configure).
 * Sequences are auto-generated by the system. Users can VIEW and CONFIGURE
 * them but not CREATE or DELETE.
 * Follows the CashAccounts.tsx design pattern.
 * Default export for lazy loading via React.lazy().
 */

import { useState, useMemo, useEffect, useRef, useCallback } from "react";
import {
  Table,
  Card,
  Row,
  Col,
  Grid,
  Typography,
  Tag,
  Statistic,
  Input,
  InputNumber,
  Select,
  Tooltip,
  Button,
  Drawer,
  Form,
  Space,
} from "antd";
import type { TableColumnsType } from "antd";
import {
  SearchOutlined,
  ReloadOutlined,
  EditOutlined,
  NumberOutlined,
  CheckCircleOutlined,
  SettingOutlined,
} from "@ant-design/icons";
import { toast } from "sonner";

import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { EmptyState } from "@/components/common/EmptyState";
import { useTranslation } from "@/hooks/ui/useTranslation";
import { QUERY_KEYS } from "@/constants/queryKeys";
import { ROUTES } from "@/shared/constants/routes";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  sequencesService,
  type Sequence,
  type UpdateSequenceDto,
} from "@/services/sequences.service";

const { Text } = Typography;
const DEFAULT_PAGE_SIZE = 20;

// ── Constants ────────────────────────────────────────────────────────────────

const RESET_CYCLE_OPTIONS = [
  { value: "NEVER", label: "Never" },
  { value: "YEARLY", label: "Yearly" },
  { value: "MONTHLY", label: "Monthly" },
];

const RESET_CYCLE_COLORS: Record<string, string> = {
  NEVER: "default",
  YEARLY: "blue",
  MONTHLY: "orange",
  never: "default",
  yearly: "blue",
  monthly: "orange",
};

const ENTITY_LABELS: Record<string, string> = {
  SALES_ORDER: "Sales Order",
  PURCHASE_ORDER: "Purchase Order",
  SALES_INVOICE: "Sales Invoice",
  PURCHASE_INVOICE: "Purchase Invoice",
  JOURNAL_ENTRY: "Journal Entry",
  STOCK_TRANSFER: "Stock Transfer",
  CUSTOMER_RECEIPT: "Customer Receipt",
  EMPLOYEE: "Employee",
  QUOTATION: "Quotation",
  LEAVE_REQUEST: "Leave Request",
  DELIVERY: "Delivery",
  CREDIT_NOTE: "Credit Note",
  DEBIT_NOTE: "Debit Note",
};

// ── Helpers ──────────────────────────────────────────────────────────────────

function formatNextNumber(
  prefix: string,
  separator: string,
  nextValue: number,
  padding: number
): string {
  return `${prefix}${separator}${String(nextValue).padStart(padding, "0")}`;
}

// ── Component ────────────────────────────────────────────────────────────────

export default function SequenceSettings() {
  const { t, lang } = useTranslation();
  const screens = Grid.useBreakpoint();
  const isMobile = !screens.md;
  const queryClient = useQueryClient();

  // ── Search with 400ms debounce ──────────────────────────────────────────
  const [searchInput, setSearchInput] = useState("");
  const [search, setSearch] = useState("");
  const debounceRef = useRef<ReturnType<typeof setTimeout>>(undefined);

  useEffect(() => {
    debounceRef.current = setTimeout(() => {
      setSearch(searchInput);
    }, 400);
    return () => clearTimeout(debounceRef.current);
  }, [searchInput]);

  // ── State ──────────────────────────────────────────────────────────────
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE);

  // Edit drawer state
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [editingRecord, setEditingRecord] = useState<Sequence | null>(null);
  const [form] = Form.useForm();

  // ── Query ──────────────────────────────────────────────────────────────
  const {
    data: seqRaw,
    isLoading,
    refetch,
  } = useQuery({
    queryKey: [QUERY_KEYS.SEQUENCES],
    queryFn: () => sequencesService.list(),
    staleTime: 30_000,
  });

  const allSequences: Sequence[] = useMemo(() => {
    const raw = seqRaw as Record<string, unknown> | undefined;
    return (raw?.data as Sequence[]) ?? [];
  }, [seqRaw]);

  // ── Filtered data ──────────────────────────────────────────────────────
  const filteredSequences = useMemo(() => {
    if (!search.trim()) return allSequences;
    const q = search.trim().toLowerCase();
    return allSequences.filter(
      s =>
        (s.entityType ?? "").toLowerCase().includes(q) ||
        (s.prefix ?? "").toLowerCase().includes(q) ||
        (ENTITY_LABELS[s.entityType] ?? "").toLowerCase().includes(q)
    );
  }, [allSequences, search]);

  // ── KPI values ─────────────────────────────────────────────────────────
  const kpiTotal = allSequences.length;
  const kpiActive = allSequences.filter(s => s.isActive !== false).length;

  // ── Update mutation ────────────────────────────────────────────────────
  const updateMutation = useMutation({
    mutationFn: ({ id, dto }: { id: string; dto: UpdateSequenceDto }) =>
      sequencesService.update(id, dto),
    onSuccess: () => {
      toast.success(t("seq.editSuccess", lang));
      queryClient.invalidateQueries({ queryKey: [QUERY_KEYS.SEQUENCES] });
      closeDrawer();
    },
    onError: () => {
      toast.error(t("seq.editFailed", lang));
    },
  });

  // ── Drawer helpers ─────────────────────────────────────────────────────
  const openEdit = useCallback(
    (record: Sequence) => {
      setEditingRecord(record);
      form.setFieldsValue({
        prefix: record.prefix,
        padding: record.padding,
        resetCycle: (record.resetCycle ?? "NEVER").toUpperCase(),
        separator: record.separator ?? "-",
      });
      setDrawerOpen(true);
    },
    [form]
  );

  const closeDrawer = useCallback(() => {
    setDrawerOpen(false);
    setEditingRecord(null);
    form.resetFields();
  }, [form]);

  const handleSave = useCallback(async () => {
    try {
      const values = await form.validateFields();
      if (!editingRecord) return;

      updateMutation.mutate({
        id: editingRecord.id,
        dto: {
          prefix: values.prefix,
          padding: values.padding,
          resetCycle: values.resetCycle,
          separator: values.separator,
          version: editingRecord.version ?? 0,
        },
      });
    } catch {
      // form validation failed — silently handled by Ant Design
    }
  }, [form, editingRecord, updateMutation]);

  // ── Table columns ──────────────────────────────────────────────────────
  const columns: TableColumnsType<Sequence> = useMemo(
    () => [
      {
        title: t("seq.entity", lang),
        dataIndex: "entityType",
        width: 200,
        sorter: (a, b) =>
          (a.entityType ?? "").localeCompare(b.entityType ?? ""),
        render: (v: string) => (
          <Text strong>{ENTITY_LABELS[v] ?? v?.replace(/_/g, " ") ?? "—"}</Text>
        ),
      },
      {
        title: t("seq.prefix", lang),
        dataIndex: "prefix",
        width: 100,
        render: (v: string) => (
          <Tag style={{ fontFamily: "monospace", borderRadius: 4 }}>
            {v || "—"}
          </Tag>
        ),
      },
      {
        title: t("seq.nextValue", lang),
        key: "nextValue",
        width: 160,
        render: (_: unknown, r: Sequence) => (
          <Text code style={{ fontSize: 12, letterSpacing: 0.5 }}>
            {formatNextNumber(
              r.prefix ?? "",
              r.separator ?? "-",
              (r.currentValue ?? 0) + 1,
              r.padding ?? 5
            )}
          </Text>
        ),
      },
      {
        title: t("seq.padding", lang),
        dataIndex: "padding",
        width: 100,
        render: (v: number) => (
          <Text>
            {v ?? 5} {t("seq.digits", lang)}
          </Text>
        ),
      },
      {
        title: t("seq.resetCycle", lang),
        dataIndex: "resetCycle",
        width: 120,
        filters: RESET_CYCLE_OPTIONS.map(o => ({
          text: o.label,
          value: o.value,
        })),
        onFilter: (val, rec) =>
          (rec.resetCycle ?? "NEVER").toUpperCase() ===
          String(val).toUpperCase(),
        render: (v: string) => {
          const cycle = (v ?? "NEVER").toUpperCase();
          return (
            <Tag
              color={RESET_CYCLE_COLORS[cycle] ?? "default"}
              style={{ borderRadius: 20 }}
            >
              {cycle}
            </Tag>
          );
        },
      },
      {
        title: t("seq.actions", lang),
        key: "actions",
        align: "center",
        width: 80,
        fixed: "right",
        render: (_: unknown, r: Sequence) => (
          <Tooltip title={t("seq.edit", lang)}>
            <Button
              type="text"
              size="small"
              icon={<EditOutlined />}
              onClick={e => {
                e.stopPropagation();
                openEdit(r);
              }}
            />
          </Tooltip>
        ),
      },
    ],
    [t, lang, openEdit]
  );

  // ── KPI cards config ───────────────────────────────────────────────────
  const statCards = [
    {
      title: t("seq.totalSequences", lang),
      value: kpiTotal,
      icon: <NumberOutlined />,
      iconColor: "#8b5cf6",
      iconBg: "#8b5cf615",
    },
    {
      title: t("seq.totalActive", lang),
      value: kpiActive,
      icon: <CheckCircleOutlined />,
      iconColor: "#10b981",
      iconBg: "#10b98115",
    },
  ];

  const breadcrumbs = [
    { label: t("Dashboard", lang), href: ROUTES.DASHBOARD },
    { label: t("Settings", lang), href: "#" },
    { label: t("seq.title", lang) },
  ];

  // ── Render ─────────────────────────────────────────────────────────────

  return (
    <DashboardLayout currentPage="Sequence Settings" breadcrumbs={breadcrumbs}>
      <div className="flex flex-col gap-6">
        {/* ── 1. Stats Row (2 KPI cards) ──────────────────────────────────── */}
        <Row gutter={[16, 16]}>
          {statCards.map(s => (
            <Col key={s.title} xs={24} sm={12}>
              <Card size="small" styles={{ body: { padding: "16px 20px" } }}>
                <div className="flex justify-between items-start">
                  <div>
                    <Text
                      type="secondary"
                      style={{
                        fontSize: 12,
                        display: "block",
                        marginBottom: 4,
                      }}
                    >
                      {s.title}
                    </Text>
                    <Statistic
                      value={s.value}
                      valueStyle={{ fontSize: 24, lineHeight: 1 }}
                    />
                  </div>
                  <div
                    style={{
                      width: 40,
                      height: 40,
                      borderRadius: 10,
                      background: s.iconBg,
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      fontSize: 18,
                      color: s.iconColor,
                    }}
                  >
                    {s.icon}
                  </div>
                </div>
              </Card>
            </Col>
          ))}
        </Row>

        {/* ── 2. Toolbar Card ─────────────────────────────────────────────── */}
        <Card size="small" styles={{ body: { padding: "12px 16px" } }}>
          <div className="flex flex-wrap gap-2 justify-between items-center">
            <Input
              prefix={<SearchOutlined className="text-gray-400" />}
              placeholder={t("seq.searchPlaceholder", lang)}
              value={searchInput}
              onChange={e => setSearchInput(e.target.value)}
              allowClear
              style={{ width: isMobile ? "100%" : 300 }}
            />
            <Tooltip title={t("common.reload", lang)}>
              <Button icon={<ReloadOutlined />} onClick={() => refetch()} />
            </Tooltip>
          </div>
        </Card>

        {/* ── 3. Data table ───────────────────────────────────────────────── */}
        <Card styles={{ body: { padding: 0 } }}>
          <Table
            rowKey="id"
            columns={columns}
            dataSource={filteredSequences}
            loading={isLoading}
            size="middle"
            scroll={{ x: "max-content" }}
            pagination={{
              current: page,
              pageSize,
              total: filteredSequences.length,
              showSizeChanger: true,
              pageSizeOptions: ["10", "20", "50"],
              showTotal: (total, range) =>
                `${range[0]}-${range[1]} of ${total}`,
              onChange: (p, ps) => {
                setPage(p);
                setPageSize(ps);
              },
            }}
            locale={{ emptyText: <EmptyState /> }}
          />
        </Card>
      </div>

      {/* ── 4. Edit Drawer ──────────────────────────────────────────────── */}
      <Drawer
        open={drawerOpen}
        onClose={closeDrawer}
        width={isMobile ? "100%" : 420}
        title={
          <Space>
            <SettingOutlined style={{ color: "var(--ant-color-primary)" }} />
            <span>
              {t("seq.editTitle", lang)}
              {editingRecord
                ? ` — ${ENTITY_LABELS[editingRecord.entityType] ?? editingRecord.entityType}`
                : ""}
            </span>
          </Space>
        }
        extra={
          <Space>
            <Button onClick={closeDrawer}>{t("common.cancel", lang)}</Button>
            <Button
              type="primary"
              onClick={handleSave}
              loading={updateMutation.isPending}
            >
              {t("seq.saveChanges", lang)}
            </Button>
          </Space>
        }
        destroyOnClose
      >
        <Form form={form} layout="vertical">
          <Form.Item
            label={t("seq.prefix", lang)}
            name="prefix"
            rules={[
              {
                required: true,
                message: t("seq.prefixRequired", lang),
              },
            ]}
          >
            <Input
              placeholder="e.g. SO"
              maxLength={10}
              style={{ fontFamily: "monospace" }}
            />
          </Form.Item>

          <Form.Item
            label={t("seq.padding", lang)}
            name="padding"
            rules={[
              {
                required: true,
                message: t("seq.paddingRequired", lang),
              },
            ]}
          >
            <InputNumber min={1} max={10} style={{ width: "100%" }} />
          </Form.Item>

          <Form.Item
            label={t("seq.resetCycle", lang)}
            name="resetCycle"
            rules={[{ required: true }]}
          >
            <Select
              options={RESET_CYCLE_OPTIONS.map(o => ({
                value: o.value,
                label: o.label,
              }))}
            />
          </Form.Item>

          <Form.Item
            label={t("seq.separator", lang)}
            name="separator"
            rules={[{ required: true }]}
          >
            <Input
              placeholder='e.g. "-"'
              maxLength={5}
              style={{ width: 100, fontFamily: "monospace" }}
            />
          </Form.Item>

          {editingRecord && (
            <Card
              size="small"
              style={{ marginTop: 16 }}
              styles={{ body: { padding: "12px 16px" } }}
            >
              <Text type="secondary" style={{ fontSize: 12 }}>
                {t("seq.preview", lang)}
              </Text>
              <br />
              <Text
                code
                style={{ fontSize: 14, letterSpacing: 0.5, marginTop: 4 }}
              >
                {formatNextNumber(
                  form.getFieldValue("prefix") ?? editingRecord.prefix,
                  form.getFieldValue("separator") ??
                    editingRecord.separator ??
                    "-",
                  (editingRecord.currentValue ?? 0) + 1,
                  form.getFieldValue("padding") ?? editingRecord.padding ?? 5
                )}
              </Text>
              <br />
              <Text
                type="secondary"
                style={{ fontSize: 11, marginTop: 8, display: "block" }}
              >
                {t("seq.versionInfo", lang)}: v{editingRecord.version ?? 0}
              </Text>
            </Card>
          )}
        </Form>
      </Drawer>
    </DashboardLayout>
  );
}
